site_name: MA2221 â€” Foundational Mathematics for Machine Learning
site_url: https://biswarupbiswas.github.io/MA2221

theme:
  name: material
  logo: assets/MFML_logo.png
  favicon: assets/MFML_logo.png
  palette:
    scheme: default
    primary: indigo
    accent: blue
  features:
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Lectures: lectures.md
  - Tutorials: tutorials.md
  - Codes: codes.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - attr_list

extra_css:
  - stylesheets/extra.css