site_name: MA2221 â€” Foundational Mathematics for Machine Learning
site_url: https://biswarupbiswas.github.io/MA2221
copyright: Copyright &copy; 2026 Biswarup Biswas # Add this at the top level

theme:
  name: material
  custom_dir: overrides
  logo: assets/MFML_logo.png
  favicon: assets/MFML_logo.png
  palette:
    scheme: default
    primary: indigo
    accent: blue
  features:
    - navigation.sections
    - content.code.copy
    - footer.hide.generator # The "new" way

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: false
      # Note: include_mathjax is removed to avoid the 'Unrecognised' warning

nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Lectures: lectures.md
  - Tutorials: tutorials.md
  - Notebooks:
      - Lab 1: notebooks/notebook1.ipynb
  # - Codes: codes.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - attr_list

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/biswarupbiswas
    - icon: fontawesome/solid/envelope
      link: mailto:your-biswarup.biswas@mahindrauniversity.edu.in
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dr-biswarup-biswas